# Generated by Django 4.1.1 on 2022-10-03 05:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0002_chats'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chats',
            old_name='chats',
            new_name='chat',
        ),
        migrations.RemoveField(
            model_name='chats',
            name='user',
        ),
        migrations.AddField(
            model_name='chats',
            name='receipt',
            field=models.CharField(default='None', max_length=400),
        ),
        migrations.AddField(
            model_name='chats',
            name='time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
