# Generated by Django 4.1.1 on 2022-10-03 12:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0004_alter_chats_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chats',
            name='time',
            field=models.TimeField(default=datetime.datetime(2022, 10, 3, 18, 10, 26, 803941)),
        ),
    ]
