# Generated by Django 4.1.1 on 2022-10-05 03:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0009_alter_chats_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='redisuser',
            name='last_seeen',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 5, 9, 22, 32, 280125)),
        ),
        migrations.AlterField(
            model_name='chats',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 5, 9, 22, 32, 280590)),
        ),
    ]
