# Generated by Django 4.1.1 on 2022-10-05 03:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0010_redisuser_last_seeen_alter_chats_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='redisuser',
            name='last_seeen',
        ),
        migrations.AddField(
            model_name='redisuser',
            name='last_seen',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 5, 9, 24, 2, 546109)),
        ),
        migrations.AlterField(
            model_name='chats',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 5, 9, 24, 2, 546544)),
        ),
    ]
