# Generated by Django 4.1.1 on 2022-10-05 04:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0012_alter_chats_time_alter_redisuser_last_seen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chats',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 5, 9, 33, 31, 634964)),
        ),
    ]
