# Generated by Django 4.1.1 on 2022-10-05 04:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0013_alter_chats_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chats',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 5, 9, 35, 42, 551238)),
        ),
        migrations.AlterField(
            model_name='redisuser',
            name='last_seen',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 5, 9, 35, 42, 550923)),
        ),
    ]
