# Generated by Django 4.1.1 on 2022-10-06 04:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0015_remove_redisuser_last_seen_redisuser_active_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chats',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 6, 10, 10, 15, 443865)),
        ),
        migrations.AlterField(
            model_name='redisuser',
            name='active_status',
            field=models.DateTimeField(default='Online', null=True),
        ),
    ]
