# Generated by Django 4.1.1 on 2022-10-06 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0017_alter_chats_time_alter_redisuser_active_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chats',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
